// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:DarkriftExtensions.SendMessage(DarkRift.Server.IClient,System.UInt16,System.UInt16,DarkRift.SendMode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:DarkriftExtensions.SendMessageNoContent(DarkRift.Server.IClient,System.UInt16,DarkRift.SendMode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:MasterServer.DarkRift.Shared.Cryptography.Decrypt_Aes(System.Byte[],System.Byte[])~System.Byte[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:MasterServer.DarkRift.Shared.Cryptography.Encrypt_Aes(System.Byte[],System.Byte[])~System.Byte[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:MasterServer.DarkRift.Shared.Cryptography.GenerateAESKey~System.Byte[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:MasterServer.DarkRift.Shared.Cryptography.GenerateDSAParameters(System.Security.Cryptography.DSAParameters@,System.Security.Cryptography.DSAParameters@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:MasterServerManager.Authorize(System.Object,DarkRift.Server.MessageReceivedEventArgs)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:MasterServerManager.SendPublicKey(System.Object,DarkRift.Server.MessageReceivedEventArgs)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:PlayerSessionManager.ClientAuthRequest(System.Object,DarkRift.Server.MessageReceivedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:PlayerSessionManager.OnMasterServerLoginMessage(System.Object,DarkRift.Server.MessageReceivedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:PlayerSessionManager.SaveCharacterData(System.String,ConnectedPlayer)")]
